# Generated by Django 3.2.4 on 2021-06-04 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to='sms_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('receive_quantity', models.IntegerField(blank=True, null=True)),
                ('receive_by', models.CharField(max_length=30, null=True)),
                ('issue_by', models.CharField(max_length=30, null=True)),
                ('issue_quantity', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_csv', models.BooleanField(default=False)),
                ('tags_id', models.ManyToManyField(to='sms_app.Tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
