# Generated by Django 3.2.4 on 2021-06-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_remove_stock_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, db_column='Total Quantity', default=0, null=True),
        ),
    ]
