# Generated by Django 3.2.4 on 2021-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='export_to_csv',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sms_images/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
