# Generated by Django 3.2.4 on 2021-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_auto_20210605_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tags_id',
            field=models.ManyToManyField(blank=True, to='sms_app.Tag'),
        ),
    ]
