# Generated by Django 3.2.4 on 2021-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_auto_20210605_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='issue_by',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_required',
            field=models.IntegerField(null=True, verbose_name='Q Required'),
        ),
    ]
