# Generated by Django 3.2.4 on 2021-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_auto_20210605_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_calc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.IntegerField(null=True, verbose_name='Q Received'),
        ),
    ]
