# Generated by Django 3.2.4 on 2021-06-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_auto_20210605_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity_calc',
        ),
    ]
