# Generated by Django 3.2.4 on 2021-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0010_remove_stock_quantity_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_before',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
