# Generated by Django 3.2.4 on 2021-06-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0014_auto_20210606_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='export_to_csv',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
