# Generated by Django 3.2.4 on 2021-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0015_auto_20210607_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='export_to_csv',
            field=models.BooleanField(default=False),
        ),
    ]
