# Generated by Django 3.2.4 on 2021-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0019_stock_reorder_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Unit Price')),
                ('category', models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('Sport', 'Sport'), ('Accessories Auto', 'Accessories Auto'), ('Movies', 'Movies')], max_length=40, null=True, verbose_name='Category')),
                ('quantity_before', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_calc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Q')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sms_images/')),
                ('date_created', models.DateTimeField(null=True)),
                ('quantity_required', models.IntegerField(blank=True, null=True, verbose_name='Q Required')),
                ('receive_quantity', models.IntegerField(blank=True, null=True, verbose_name='Q Received')),
                ('receive_by', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_by', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField()),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('tags_id', models.ManyToManyField(blank=True, to='sms_app.Tag')),
            ],
        ),
    ]
